// Run against python -m tests.preview_practice with Playwright on NODE_PATH.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({channel:'msedge', headless:true});
  const context = await browser.newContext({viewport:{width:390,height:844}, acceptDownloads:true});
  const page = await context.newPage(), errors = [];
  page.on('pageerror', error => errors.push(error.message));
  try {
    await page.goto('http://127.0.0.1:8766/phone#practice-preview-controller-token');
    await page.getByText('已连接', {exact:true}).waitFor();
    await page.getByRole('tab', {name:'练习复盘'}).click();
    await page.getByRole('button', {name:'录我的回答', exact:true}).click();
    await page.getByText('麦克风开启', {exact:true}).waitFor();
    await page.waitForFunction(() => document.querySelector('#practice-answer').value.includes('接口测试'));
    await page.request.post('http://127.0.0.1:8766/api/ask', {data:{question:'下一道测试问题'}});
    assert.equal(await page.locator('#practice-question').inputValue(), 'practice-q1');
    await page.getByRole('button', {name:'结束录音并转写'}).click();
    await page.waitForFunction(() => !document.querySelector('#practice-answer').disabled);
    assert((await page.locator('#practice-answer').inputValue()).includes('回归用例'));
    await page.locator('#practice-answer').fill('我负责接口测试，复现问题后编写回归用例，并核对修复结果。');
    await page.getByRole('button', {name:'生成复盘 →', exact:true}).click();
    await page.getByText('复盘完成', {exact:true}).waitFor();
    assert((await page.locator('#practice-review-text').textContent()).includes('核对修复结果'));
    const downloadEvent = page.waitForEvent('download');
    await page.getByRole('button', {name:'导出复盘'}).click();
    const download = await downloadEvent;
    const output = path.resolve('.local'); fs.mkdirSync(output, {recursive:true});
    await download.saveAs(path.join(output, 'practice-test-export.md'));
    assert(fs.readFileSync(path.join(output, 'practice-test-export.md'), 'utf8').includes('实际回答（生成时版本）'));
    await page.reload();
    await page.getByText('已连接', {exact:true}).waitFor();
    await page.getByRole('tab', {name:'练习复盘'}).click();
    await page.locator('#practice-question').selectOption('practice-q1');
    await page.getByText('复盘完成', {exact:true}).waitFor();
    assert((await page.locator('#practice-answer').inputValue()).includes('核对修复结果'));
    await page.locator('#practice-answer').fill('校正后的真实回答');
    await page.getByRole('button', {name:'保存文字', exact:true}).click();
    await page.waitForFunction(() => !document.querySelector('#practice-review-text').textContent.includes('模拟复盘'));
    await page.getByRole('button', {name:'生成复盘 →', exact:true}).click();
    await page.getByText('复盘完成', {exact:true}).waitFor();
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({path:path.join(output, 'practice-mobile.png'), fullPage:true});
    await page.getByRole('tab', {name:'监听设置'}).click();
    await page.getByRole('button', {name:'开始检查', exact:true}).click();
    await page.getByText('✓ 电脑后台', {exact:true}).waitFor();
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({path:path.join(output, 'diagnostics-mobile.png'), fullPage:true});
    await page.getByRole('tab', {name:'练习复盘'}).click();
    await page.getByText('添加练习题（无需请求模型）', {exact:true}).click();
    await page.locator('#practice-new-question').fill('如果无法复现，你会如何继续排查？');
    await page.getByRole('button', {name:'添加练习题', exact:true}).click();
    await page.waitForFunction(() => document.querySelector('#practice-question-text').textContent === '如果无法复现，你会如何继续排查？');
    assert.equal(await page.locator('#practice-answer').inputValue(), '');
    await page.goto('http://127.0.0.1:8766/');
    await page.getByRole('button', {name:'检测设备与连接'}).click();
    await page.getByText('✓ 电脑后台', {exact:true}).waitFor();
    await page.screenshot({path:path.join(output, 'onboarding-mobile.png'), fullPage:true});
    assert.deepEqual(errors, []);
    console.log('PASS: microphone -> final flush -> correction -> review -> export -> reload -> invalidation -> next practice question; phone and desktop diagnostics; 390px layout; no browser errors');
  } finally { await browser.close(); }
})().catch(error => {console.error(error); process.exitCode = 1;});
